kafka {
  bootstrap.servers = "localhost:9092"
  topic = "sensores-data"
  group.id = "streaming-app-group"
}

spark {
  app.name = "KafkaConsumer"
  bronze.checkpoint.location = "C:/tmp/spark-checkpoint-bronze"
  silver.checkpoint.location = "C:/tmp/spark-checkpoint-silver"
  bronze.path = "C:/datos/raw_temperaturas"
  silver.path = "C:/datos/temperaturas_altas"
}

hadoop {
  home.dir = "C:/hadoop"
}