kafka {
  bootstrap.servers = ${?KAFKA_BOOTSTRAP_SERVERS}
  bootstrap.servers = "localhost:9092"

  topic = ${?KAFKA_TOPIC}
  topic = "sensores-data"

  group.id = ${?KAFKA_GROUP_ID}
  group.id = "streaming-app-group"
}

spark {
  app.name = ${?SPARK_APP_NAME}
  app.name = "KafkaConsumer"

  bronze.checkpoint.location = ${?BRONZE_CHECKPOINT_DIR}
  bronze.checkpoint.location = "./checkpoints/bronze"

  silver.checkpoint.location = ${?SILVER_CHECKPOINT_DIR}
  silver.checkpoint.location = "./checkpoints/silver"

  gold.checkpoint.location = ${?GOLD_CHECKPOINT_DIR}
  gold.checkpoint.location = "./checkpoints/gold"

  bronze.path = ${?BRONZE_PATH}
  bronze.path = "./data/bronze"

  silver.path = ${?SILVER_PATH}
  silver.path = "./data/silver"

  gold.path = ${?GOLD_PATH}
  gold.path = "./data/gold"
}

hadoop {
  home.dir = ${?HADOOP_HOME_DIR}
  home.dir = "C:/hadoop"
}